version: '3.9'

services:  
  black_list:
    container_name: black_list
    build: .
    ports:
      - "6666:6666"
    networks:
      - ntwrk
    environment:
      - DB_HOST=postgresdb
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=feruza1727
      - DB_NAME=black_list

volumes:
  db:

networks:
  ntwrk:
    external: true
    name: ntwrk
    driver: bridge